AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Acts as a scribe for doctors
Resources:
  AlexaSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: alexa-scribe/index.handler
      Runtime: nodejs6.10
      CodeUri: s3://midwest-hackathon/alexa-scribe.zip
      AutoPublishAlias: live
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          AppId: amzn1.ask.skill.22e6e083-10d3-47d1-a5a3-4ff131f04c5d
  DDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "PatientId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "PatientId"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "ScribePatients"
