pipeline:
  name: alexa-scribe-infrastructure-pipeline
  roleArn: arn:aws:iam::410717277537:role/alexa-scribe-infrastructure-codepipeline-role
  artifactStore:
    type: S3
    location: codepipeline-us-east-1-285665459630
  stages:
  - name: Source
    actions:
    - name: Source
      actionTypeId:
        category: Source
        owner: ThirdParty
        provider: GitHub
        version: '1'
      runOrder: 1
      configuration:
        Branch: master
        OAuthToken: "****"
        Owner: Lusey77
        PollForSourceChanges: 'false'
        Repo: midwest-hackathon-infrastructure
      outputArtifacts:
      - name: MyApp
      inputArtifacts: []
  - name: Staging
    actions:
    - name: alexa-scribe-infrastructure-create-change-set
      actionTypeId:
        category: Deploy
        owner: AWS
        provider: CloudFormation
        version: '1'
      runOrder: 1
      configuration:
        ActionMode: CHANGE_SET_REPLACE
        Capabilities: CAPABILITY_IAM
        ChangeSetName: alexa-scribe-infrastructure-changeset
        RoleArn: arn:aws:iam::410717277537:role/Lambda-Super-Execute
        StackName: alexa-scribe-infrastructure-stack
        TemplatePath: MyApp::alexa-scribe-infrastructure-template.yaml
      outputArtifacts: []
      inputArtifacts:
      - name: MyApp
    - name: AdminApproval
      actionTypeId:
        category: Approval
        owner: AWS
        provider: Manual
        version: '1'
      runOrder: 2
      configuration:
        NotificationArn: arn:aws:sns:us-east-1:410717277537:CodeCommitBuildApproval
      outputArtifacts: []
      inputArtifacts: []
    - name: alexa-scribe-infrastructure-execute-change-set
      actionTypeId:
        category: Deploy
        owner: AWS
        provider: CloudFormation
        version: '1'
      runOrder: 3
      configuration:
        ActionMode: CHANGE_SET_EXECUTE
        ChangeSetName: alexa-scribe-infrastructure-changeset
        StackName: alexa-scribe-infrastructure-stack
      outputArtifacts: []
      inputArtifacts:
      - name: MyApp
  version: 5
metadata:
  pipelineArn: arn:aws:codepipeline:us-east-1:410717277537:alexa-scribe-infrastructure-pipeline
  created: 1526685652.692
  updated: 1526955167.997
